### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by roblourens** [timmyreilly/TypewriterNoises-VSCode#1]
This is awesome! I was trying to do something similar and decided playing audio in Windows was too much effort. What goes into play.exe?

**Comment by timmyreilly** [comment]
I found sWavPlayer from [Skwire](http://skwire.dcmembers.com/wb/pages/software/swavplayer.php) off the [DonationCoder.com](http://www.donationcoder.com/forum/index.php?topic=27254.0) forums!
